apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: social-network
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
        image: bitnami/mongodb-exporter:latest
        args:
        - --mongodb.uri=mongodb://mongodb:27017
        ports:
        - containerPort: 9216
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: social-network
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
  - port: 9216
    targetPort: 9216
