apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-service-config
  namespace: social-network
data:
  MONGODB_URI: "mongodb://admin:password@mongodb:27017/social-network?authSource=admin"
  KAFKA_BROKERS: "kafka:9092"
  POSTS_SERVICE_PORT: "3020"