apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
  namespace: social-network
  labels:
    app: posts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
      - name: posts-service
        image: rania290/projet-micro-posts-service:latest
        ports:
        - containerPort: 3020
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password@mongodb:27017/social-network?authSource=admin"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: POSTS_SERVICE_PORT
          value: "3020"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /posts
            port: 3020
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /posts
            port: 3020
          initialDelaySeconds: 5
          periodSeconds: 5
