apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: social-network
  labels:
    app: posts-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3020"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: posts-service
  ports:
  - port: 3020
    targetPort: 3020
  type: ClusterIP