apiVersion: v1
kind: Service
metadata:
  name: posts-service
  namespace: social-network
  labels:
    app: posts-service
spec:
  selector:
    app: posts-service
  ports:
  - port: 3020
    targetPort: 3020
  type: ClusterIP