apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-network.fullname" . }}-chat-service
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: chat-service
spec:
  type: {{ .Values.chatService.service.type }}
  ports:
  - port: {{ .Values.chatService.port }}
    targetPort: {{ .Values.chatService.port }}
    protocol: TCP
    name: grpc
  - port: {{ .Values.chatService.metricsPort }}
    targetPort: {{ .Values.chatService.metricsPort }}
    protocol: TCP
    name: metrics
  selector:
    {{- include "social-network.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: chat-service
