apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-network.fullname" . }}-grafana
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.port }}
    targetPort: {{ .Values.grafana.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "social-network.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana