apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-network.fullname" . }}-graphql-service
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql-service
spec:
  type: {{ .Values.graphqlService.service.type }}
  ports:
  - port: {{ .Values.graphqlService.port }}
    targetPort: {{ .Values.graphqlService.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "social-network.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: graphql-service