apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-network.fullname" . }}-kafka
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: {{ .Values.kafka.service.port }}
    protocol: TCP
    name: kafka
  - port: 9308
    targetPort: 9308
    protocol: TCP
    name: metrics
  selector:
    {{- include "social-network.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
