apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-network.fullname" . }}-zookeeper
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
  - port: {{ .Values.zookeeper.service.port }}
    targetPort: {{ .Values.zookeeper.service.port }}
    protocol: TCP
    name: zookeeper
  selector:
    {{- include "social-network.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
