apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: social-network
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'social-network-services'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - social-network
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: '.*'
            target_label: service
            replacement: '$1'
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: '.*'
            target_label: port
            replacement: '$1'
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: '$1:$2'
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            target_label: __address__
            replacement: '$1'