apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-network
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rania290/projet-micro.git
    targetRevision: HEAD
    path: helm/social-network
  destination:
    server: https://kubernetes.default.svc
    namespace: social-network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
