apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-network-mongodb-pvc
  namespace: social-network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-network-kafka-pvc
  namespace: social-network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-network-zookeeper-pvc
  namespace: social-network
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
