apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "social-network.fullname" . }}-mongodb-pvc
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | default "10Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "social-network.fullname" . }}-kafka-pvc
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.persistence.size | default "10Gi" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "social-network.fullname" . }}-zookeeper-pvc
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zookeeper.persistence.size | default "5Gi" }}
