apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  namespace: social-network
  labels:
    app: graphql-service
spec:
  selector:
    app: graphql-service
  ports:
  - port: 4000
    targetPort: 4000
  type: LoadBalancer