apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "social-network.fullname" . }}-prometheus
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus