apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "social-network.fullname" . }}-grafana-config
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "social-network.fullname" . }}-prometheus:{{ .Values.prometheus.port }}
      isDefault: true
      editable: true