apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "social-network.fullname" . }}-prometheus-config
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'posts-service'
        static_configs:
          - targets: ['{{ include "social-network.fullname" . }}-posts-service:{{ .Values.postsService.port }}']

      - job_name: 'graphql-service'
        static_configs:
          - targets: ['{{ include "social-network.fullname" . }}-graphql-service:{{ .Values.graphqlService.port }}']

      - job_name: 'chat-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['{{ include "social-network.fullname" . }}-chat-service:{{ .Values.chatService.port }}']

      - job_name: 'mongodb'
        static_configs:
          - targets: ['{{ include "social-network.fullname" . }}-mongodb:{{ .Values.mongodb.port }}']

      - job_name: 'kafka'
        static_configs:
          - targets: ['{{ include "social-network.fullname" . }}-kafka:{{ .Values.kafka.port }}']