apiVersion: v1
kind: Secret
metadata:
  name: {{ include "social-network.fullname" . }}-grafana-secret
  labels:
    {{- include "social-network.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}